'use client';
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, BookOpen, Calendar, DollarSign, Hotel, TrendingDown, TrendingUp } from 'lucide-react';
import toast from 'react-hot-toast';
import { analyticsApi, getApiData, getApiError } from '@/lib/api';

type Report = { year:number; month:number; kpis:{ revenue:number; revenueGrowth:number; occupancyRate:number; occupancyGrowth:number; averageDailyRate:number; adrGrowth:number; totalBookings:number; bookingGrowth:number }; monthlyRevenue:{year:number;month:number;revenue:number;bookings:number}[]; revenueByBrand:{brandName:string;revenue:number;bookings:number;percentage:number}[]; roomPerformance:{roomId:string;roomName:string;propertyName:string;brandName:string;nightsBooked:number;revenue:number;occupancyRate:number}[] };
const money = new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 0 });
const colors = ['#D24A15','#be123c','#6b7280','#f59e0b','#0f766e','#7c3aed'];

export default function AdminPage() {
  const today = new Date();
  const [period,setPeriod] = useState(`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`);
  const [report,setReport] = useState<Report|null>(null);
  const [loading,setLoading] = useState(true);
  useEffect(() => { const [year,month]=period.split('-').map(Number); setLoading(true); analyticsApi.getReport(year,month).then(r=>setReport(getApiData(r) as Report|null)).catch(e=>toast.error(getApiError(e))).finally(()=>setLoading(false)); },[period]);
  const maxRevenue=Math.max(1,...(report?.monthlyRevenue.map(x=>x.revenue)??[1]));
  const donut=useMemo(()=>{let cursor=0;const stops=(report?.revenueByBrand??[]).map((x,i)=>{const start=cursor;cursor+=x.percentage;return `${colors[i%colors.length]} ${start}% ${cursor}%`});return stops.length?`conic-gradient(${stops.join(',')})`:'#e5e7eb'},[report]);
  const exportCsv=()=>{if(!report)return;const rows=[['Tên phòng','Căn nhà','Thương hiệu','Số đêm đã đặt','Doanh thu','Công suất'],...report.roomPerformance.map(x=>[x.roomName,x.propertyName,x.brandName,x.nightsBooked,x.revenue,`${x.occupancyRate}%`])];const csv='\uFEFF'+rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download=`bao-cao-${period}.csv`;link.click();URL.revokeObjectURL(link.href)};
  const cards=report?[
    {label:'Doanh thu',value:`${money.format(report.kpis.revenue)} đ`,growth:report.kpis.revenueGrowth,icon:DollarSign,tone:'bg-orange-100 text-[#D24A15]'},
    {label:'Công suất phòng',value:`${report.kpis.occupancyRate}%`,growth:report.kpis.occupancyGrowth,icon:Hotel,tone:'bg-rose-100 text-rose-600'},
    {label:'Giá trung bình/đêm (ADR)',value:`${money.format(report.kpis.averageDailyRate)} đ`,growth:report.kpis.adrGrowth,icon:BarChart3,tone:'bg-gray-100 text-gray-600'},
    {label:'Tổng lượt đặt',value:money.format(report.kpis.totalBookings),growth:report.kpis.bookingGrowth,icon:BookOpen,tone:'bg-orange-100 text-[#D24A15]'}]:[];
  return <main className="min-h-screen px-4 py-6 sm:px-6 lg:px-10 xl:px-16 lg:py-10">
    <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="font-serif text-3xl text-gray-900 sm:text-4xl">Báo cáo & Phân tích</h1><p className="mt-2 text-gray-500">Dữ liệu thực tế từ các yêu cầu đặt phòng đã được xác nhận.</p></div><label className="flex items-center gap-3 rounded-lg border border-gray-200 bg-white px-4 py-2"><Calendar className="h-4 w-4 text-gray-500"/><input type="month" value={period} onChange={e=>setPeriod(e.target.value)} className="bg-transparent text-sm outline-none"/></label></div>
    {loading?<div className="rounded-xl border bg-white p-12 text-center text-gray-500">Đang tải dữ liệu báo cáo...</div>:!report?<div className="rounded-xl border bg-white p-12 text-center text-gray-500">Không tải được dữ liệu báo cáo.</div>:<>
      <section className="mb-8 grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card=>{const positive=card.growth>=0;const Trend=positive?TrendingUp:TrendingDown;return <article key={card.label} className="rounded-xl border border-gray-200 bg-white p-6"><div className="mb-4 flex items-start justify-between"><span className="text-sm text-gray-500">{card.label}</span><span className={`rounded-lg p-2 ${card.tone}`}><card.icon className="h-4 w-4"/></span></div><strong className="block text-2xl text-gray-900">{card.value}</strong><div className={`mt-2 flex items-center gap-1 text-sm ${positive?'text-green-600':'text-red-600'}`}><Trend className="h-4 w-4"/>{positive?'+':''}{card.growth}% <span className="ml-1 text-gray-500">so với tháng trước</span></div></article>})}</section>
      <section className="mb-8 grid grid-cols-1 gap-6 lg:grid-cols-3"><article className="rounded-xl border border-gray-200 bg-white p-6 lg:col-span-2"><h2 className="mb-6 font-medium">Xu hướng doanh thu 6 tháng</h2><div className="flex h-72 items-end gap-3 border-b border-gray-200 px-2 sm:gap-6">{report.monthlyRevenue.map(row=><div key={`${row.year}-${row.month}`} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-xs text-gray-500">{money.format(row.revenue)}</span><div className="w-full max-w-16 rounded-t-md bg-[#D24A15]" style={{height:`${Math.max(row.revenue?5:1,row.revenue/maxRevenue*78)}%`}} title={`${row.bookings} lượt đặt`}/><span className="pb-2 text-xs text-gray-600">T{row.month}/{String(row.year).slice(-2)}</span></div>)}</div></article>
      <article className="rounded-xl border border-gray-200 bg-white p-6"><h2 className="mb-6 font-medium">Doanh thu theo thương hiệu</h2><div className="mx-auto h-44 w-44 rounded-full p-10" style={{background:donut}}><div className="flex h-full w-full items-center justify-center rounded-full bg-white text-center text-xs text-gray-500">{money.format(report.kpis.revenue)} đ</div></div><div className="mt-6 space-y-3">{report.revenueByBrand.length===0?<p className="text-center text-sm text-gray-500">Chưa có doanh thu trong kỳ.</p>:report.revenueByBrand.map((brand,i)=><div key={brand.brandName} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2"><i className="h-3 w-3 rounded-full" style={{background:colors[i%colors.length]}}/>{brand.brandName}</span><span className="font-medium">{brand.percentage}%</span></div>)}</div></article></section>
      <section className="overflow-hidden rounded-xl border border-gray-200 bg-white"><div className="flex items-center justify-between border-b p-6"><h2 className="font-medium">Báo cáo chi tiết theo phòng</h2><button onClick={exportCsv} className="text-sm font-medium text-[#D24A15] hover:underline">Xuất dữ liệu (CSV)</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-6 py-4">Tên phòng / Căn nhà</th><th className="px-6 py-4">Thương hiệu</th><th className="px-6 py-4 text-right">Số đêm</th><th className="px-6 py-4 text-right">Doanh thu</th><th className="px-6 py-4 text-right">Công suất</th></tr></thead><tbody className="divide-y">{report.roomPerformance.length===0?<tr><td colSpan={5} className="px-6 py-12 text-center text-gray-500">Chưa có phòng phát sinh doanh thu trong kỳ.</td></tr>:report.roomPerformance.map(room=><tr key={room.roomId} className="hover:bg-gray-50"><td className="px-6 py-4"><strong className="block">{room.roomName}</strong><span className="text-xs text-gray-500">{room.propertyName}</span></td><td className="px-6 py-4">{room.brandName}</td><td className="px-6 py-4 text-right">{room.nightsBooked}</td><td className="px-6 py-4 text-right font-medium">{money.format(room.revenue)} đ</td><td className="px-6 py-4 text-right font-medium">{room.occupancyRate}%</td></tr>)}</tbody></table></div></section>
    </>}
  </main>;
}
